<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="PhotinoX" Version="5.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\YStreamUtils\YStreamUtils.csproj" />
    </ItemGroup>

    <Target Name="CompileSvelteForDesktop" BeforeTargets="Build" Condition="Exists('..\frontend\package.json')">
        <Exec Command="npm install" WorkingDirectory="..\frontend" />
        <Exec Command="npm run build" WorkingDirectory="..\frontend" />
        <ItemGroup>
            <FrontendFiles Include="..\frontend\dist\**\*" />
        </ItemGroup>
        <Copy SourceFiles="@(FrontendFiles)"
              DestinationFolder="$(TargetDir)wwwroot\%(RecursiveDir)"
              SkipUnchangedFiles="true" />
    </Target>

</Project>
