<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
        <PackageReference Include="Google.Apis.YouTube.v3" Version="1.76.0.4262" />
        <PackageReference Include="Google.Protobuf" Version="3.36.1" />
        <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
        <PackageReference Include="Grpc.Tools" Version="2.84.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Jint" Version="4.16.2" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\stream_list.proto" GrpcServices="Client" />
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <Target Name="EnsureNpmInstall" BeforeTargets="Build" Condition="Exists('frontend-sk\package.json') And !Exists('frontend-sk\node_modules')">
        <Message Importance="high" Text="Installing frontend dependencies using 'npm install'..." />
        <Exec Command="npm install" WorkingDirectory="frontend-sk" />
    </Target>

    <ItemGroup>
        <Compile Remove="..\frontend-sk\node_modules\**" />
        <Compile Remove="..\frontend-sk\build\**" />
    </ItemGroup>

    <Target Name="PublishFrontend" AfterTargets="ComputeFilesToPublish">
        <Exec Command="npm install" WorkingDirectory="..\frontend-sk" />
        <Exec Command="npm run build" WorkingDirectory="..\frontend-sk" />

        <ItemGroup>
            <DistFiles Include="..\frontend\build\**\*" />
            <ResolvedFileToPublish Include="@(DistFiles)">
                <RelativePath>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
                <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
                <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            </ResolvedFileToPublish>
        </ItemGroup>
    </Target>

</Project>
