version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: ystream_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordpassword123
      POSTGRES_DB: ystreamutils
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: