/**
 * Automatically generated by YStreamUtils Go Engine.
 * Core Host System API Bindings (Git-Tracked).
 */

declare namespace host {
    function log(level: 'info' | 'warn' | 'error', message: string): void;
}
