// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum EventKey {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventKeyManualInvoke = "app:manual",

    EventKeyStreamChatMessage = "stream:chat_message",

    EventKeyYoutubeSuperchat = "stream:youtube:superchat",

    EventKeyApplicationLog = "app:log",
};

export enum Platform {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlatformTwitch = "twitch",
    PlatformYouTube = "youtube",
    PlatformKick = "kick",
};

export interface ScriptRecord {
    "ID": string;
    "EventKey": EventKey;
    "SourceCode": string;
    "UpdatedAt": string;
}

export interface UserProfile {
    "displayName": string;
    "avatarUrl": string;
    "channelID": string;
    "handle": string;
}
