// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Platform {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Youtube = "youtube",
    Twitch = "twitch",
};

export interface UserProfile {
    "displayName": string;
    "avatarUrl": string;
}
