// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YStreamUtils.Core.Data;

#nullable disable

namespace YStreamUtils.Core.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260917163936_Initial_sqlite")]
    partial class Initial_sqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthConfig", b =>
                {
                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Platform");

                    b.ToTable("OAuthConfigs");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthToken", b =>
                {
                    b.Property<int>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Platform", "IsBot");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.UserScript", b =>
                {
                    b.Property<string>("ScriptId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Topic")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScriptId");

                    b.ToTable("UserScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
