// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Module is a sandboxed, ready to execute Wasm module. This can be used to get exported functions, etc.
 * 
 * In WebAssembly terminology, this corresponds to a "Module Instance", but wazero calls pre-instantiation module as
 * "Compiled Module" as in wazero.CompiledModule, therefore we call this post-instantiation module simply "Module".
 * See https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#module-instances%E2%91%A0
 * 
 * # Notes
 * 
 *   - This is an interface for decoupling, not third-party implementations.
 *     All implementations are in wazero.
 *   - Closing the wazero.Runtime closes any Module it instantiated.
 */
export type Module = any;
