// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ports$0 from "../ports/models.js";

export function GetProfile(platform: models$0.Platform): $CancellablePromise<models$0.UserProfile | null> {
    return $Call.ByID(1432339492, platform);
}

export function LoginPlatform(platform: models$0.Platform): $CancellablePromise<boolean> {
    return $Call.ByID(3932922861, platform);
}

export function RegisterProfileDriver(platform: models$0.Platform, provider: ports$0.StreamProfileDriver): $CancellablePromise<void> {
    return $Call.ByID(2844645235, platform, provider);
}
