// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ports$0 from "../ports/models.js";

export function RegisterDriver(platform: string, d: ports$0.StreamChatDriver): $CancellablePromise<void> {
    return $Call.ByID(3211888466, platform, d);
}

export function StartChatStream(platform: string, channelID: string): $CancellablePromise<void> {
    return $Call.ByID(3931500797, platform, channelID);
}

export function StopChatPipeline(platform: string, channelID: string): $CancellablePromise<void> {
    return $Call.ByID(651163865, platform, channelID);
}
