// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function DeleteScript(id: string): $CancellablePromise<number> {
    return $Call.ByID(2291425542, id);
}

export function FindAllScripts(): $CancellablePromise<models$0.ScriptRecord[] | null> {
    return $Call.ByID(2029939280);
}

export function GetCache(key: string): $CancellablePromise<string> {
    return $Call.ByID(774742792, key);
}

export function LoadScript(id: string): $CancellablePromise<models$0.ScriptRecord | null> {
    return $Call.ByID(3849704845, id);
}

export function SaveScript(id: string, source: string, event: models$0.EventKey): $CancellablePromise<void> {
    return $Call.ByID(3622296556, id, source, event);
}

export function SetCache(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1629302372, key, value);
}
