// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ports$0 from "../ports/models.js";

export function FetchConcurrentViewers(platform: string, channelID: string): $CancellablePromise<number> {
    return $Call.ByID(1088010794, platform, channelID);
}

export function GetActiveBroadcastVideoIDs(platform: string, includeUpcoming: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(1195057988, platform, includeUpcoming);
}

export function RegisterDriver(platform: string, d: ports$0.StreamMetricsDriver): $CancellablePromise<void> {
    return $Call.ByID(3810090805, platform, d);
}
