// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export interface ActivePlugin {
    "Name": string;
    "JavaScriptCode": string;
    "TypeScriptDefs": string;
    "Functions": string[] | null;
    "Manifest": models$0.PluginManifest;
}

export interface Settings {
    "UISettings": UISettings;
}

export interface UISettings {
    "Theme": string;
    "Color": string;
    "FullCloseSidebar": boolean;
}
