// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../YStreamUtils-Plugin-Registry/ci/types/models.js";

export interface OAuthConfig {
    "client_id": string;
    "client_secret": string;
}

export interface Plugin {
    "JavaScriptCode": string;
    "TypeScriptDefs": string;
    "Manifest": types$0.PluginManifest;
}

export interface PluginSettings {
    "Repositories": string[] | null;
}

export interface Settings {
    "UISettings": UISettings;
    "PluginSettings": PluginSettings;
}

export interface UISettings {
    "Theme": string;
    "Color": string;
    "FullCloseSidebar": boolean;
}
