// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../YStreamUtils-Plugin-Registry/ci/types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DownloadAndInstallPlugin(manifest: types$0.PluginManifest): $CancellablePromise<void> {
    return $Call.ByID(1452063055, manifest);
}

export function FetchAllRegistryPlugins(): $CancellablePromise<types$0.PluginManifest[] | null> {
    return $Call.ByID(2777702260);
}

export function GetActivePlugins(): $CancellablePromise<$models.ActivePlugin[] | null> {
    return $Call.ByID(718559694);
}

export function ReloadLocalPlugins(): $CancellablePromise<void> {
    return $Call.ByID(1929561816);
}

export function StartDevPluginWatcher(onReload: any): $CancellablePromise<void> {
    return $Call.ByID(896991664, onReload);
}
