// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetManifest(): $CancellablePromise<{ [_ in string]?: $models.Script | null } | null> {
    return $Call.ByID(3871243127);
}

export function LoadScript(scriptId: string): $CancellablePromise<$models.Script | null> {
    return $Call.ByID(805530881, scriptId);
}

export function SaveScript(scriptId: string, source: string, event: models$0.EventKey): $CancellablePromise<void> {
    return $Call.ByID(4277292488, scriptId, source, event);
}
