// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../YStreamUtils-Plugin-Registry/ci/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goja$0 from "../../../../dop251/goja/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateScopedHostObject(vm: goja$0.Runtime | null, pluginName: string, permissions: types$0.Permission[] | null): $CancellablePromise<goja$0.$Object | null> {
    return $Call.ByID(3821519586, vm, pluginName, permissions);
}

export function GetDynamicPluginDefinitions(): $CancellablePromise<string> {
    return $Call.ByID(2905684001);
}

export function GetMonacoEnvironment(topic: string): $CancellablePromise<string> {
    return $Call.ByID(1463871715, topic);
}

export function InitializeVMPool(): $CancellablePromise<void> {
    return $Call.ByID(3005730738);
}

export function RegisterScriptAndBindToBus(topic: models$0.EventKey, scriptID: string, rawJsString: string): $CancellablePromise<void> {
    return $Call.ByID(3684221790, topic, scriptID, rawJsString);
}
