// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.Settings | null> {
    return $Call.ByID(3431933679);
}

export function LoadSettings(): $CancellablePromise<void> {
    return $Call.ByID(3437997003);
}

export function SaveSettings(settings: $models.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1966307142, settings);
}
