// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oauth2$0 from "../../../../../golang.org/x/oauth2/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteSession(platform: models$0.Platform): $CancellablePromise<void> {
    return $Call.ByID(1853837492, platform);
}

export function GetConfig(platform: models$0.Platform): $CancellablePromise<oauth2$0.Config | null> {
    return $Call.ByID(4212212247, platform);
}

export function GetTokenSource(platform: models$0.Platform): $CancellablePromise<oauth2$0.TokenSource> {
    return $Call.ByID(2190631775, platform);
}

export function GetValidSession(platform: models$0.Platform): $CancellablePromise<oauth2$0.Token | null> {
    return $Call.ByID(3177895331, platform);
}

export function StoreConfig(platform: models$0.Platform, cfg: $models.OAuthConfig): $CancellablePromise<void> {
    return $Call.ByID(776980594, platform, cfg);
}

export function StoreSession(platform: models$0.Platform, token: oauth2$0.Token | null): $CancellablePromise<void> {
    return $Call.ByID(2227994064, platform, token);
}
