// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ConnectChat(videoId: string): $CancellablePromise<void> {
    return $Call.ByID(3433875382, videoId);
}

export function CreateClient(): $CancellablePromise<void> {
    return $Call.ByID(3983989701);
}

export function FindActiveBroadcastVideoIDs(includeUpcoming: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(253893873, includeUpcoming);
}

export function GetConcurrentViewers(channelID: string): $CancellablePromise<number> {
    return $Call.ByID(1972737078, channelID);
}

export function GetLiveChatID(videoID: string): $CancellablePromise<string> {
    return $Call.ByID(2151448199, videoID);
}

export function GetProfile(): $CancellablePromise<models$0.UserProfile | null> {
    return $Call.ByID(3781084915);
}

export function SendChannelReply(liveChatID: string, authorID: string, replyText: string): $CancellablePromise<void> {
    return $Call.ByID(3095995661, liveChatID, authorID, replyText);
}

export function SendMessage(liveChatID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1820558823, liveChatID, message);
}
