// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YStreamUtils.Core.Data;

#nullable disable

namespace YStreamUtils.Core.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260917163941_Initial_postgres")]
    partial class Initial_postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthConfig", b =>
                {
                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Platform");

                    b.ToTable("OAuthConfigs");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthToken", b =>
                {
                    b.Property<int>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Platform", "IsBot");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.UserScript", b =>
                {
                    b.Property<string>("ScriptId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Topic")
                        .HasColumnType("integer");

                    b.HasKey("ScriptId");

                    b.ToTable("UserScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
