// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YStreamUtils.Core.Data;

#nullable disable

namespace YStreamUtils.Core.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YStreamUtils.Core.Entities.Cache", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Caches");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthConfig", b =>
                {
                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Platform");

                    b.ToTable("OAuthConfigs");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.OAuthToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<bool>("IsBotAccount")
                        .HasColumnType("boolean");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("TokenJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TokenId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("YStreamUtils.Core.Entities.UserScript", b =>
                {
                    b.Property<string>("ScriptId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Topic")
                        .HasColumnType("integer");

                    b.HasKey("ScriptId");

                    b.ToTable("UserScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
