// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DocumentationConfig {
    "Description": string;
}

export type Permission = string;

export interface PluginManifest {
    "Name": string;
    "Version": string;
    "EntryPoint": string;
    "Permissions": Permission[] | null;
    "Authors": string[] | null;
    "Source": SourceConfig;
    "Documentation": DocumentationConfig;
}

export interface SourceConfig {
    "Repository": string;
    "Owner": string;
}
