// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Publish(eventType: string, payload: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(3853013798, eventType, payload);
}

export function Subscribe(eventType: string, handler: $models.EventHandler<{ [_ in string]?: any } | null>): $CancellablePromise<void> {
    return $Call.ByID(1870511905, eventType, handler);
}
