// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type EventHandler<T> = any;

export interface Settings {
    "UISettings": UISettings;
}

export interface UISettings {
    "Theme": string;
    "Color": string;
}
