// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetDynamicPluginDefinitions(): $CancellablePromise<string> {
    return $Call.ByID(2333173495);
}

export function RegisterScriptAndBindToBus(topic: string, scriptID: string, rawJsString: string): $CancellablePromise<void> {
    return $Call.ByID(716056716, topic, scriptID, rawJsString);
}
