// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Token represents the credentials used to authorize
 * the requests to access protected resources on the OAuth 2.0
 * provider's backend.
 * 
 * Most users of this package should not access fields of Token
 * directly. They're exported mostly for use by related packages
 * implementing derivative OAuth2 flows.
 */
export interface Token {
    /**
     * AccessToken is the token that authorizes and authenticates
     * the requests.
     */
    "access_token": string;

    /**
     * TokenType is the type of token.
     * The Type method returns either this or "Bearer", the default.
     */
    "token_type"?: string;

    /**
     * RefreshToken is a token that's used by the application
     * (as opposed to the user) to refresh the access token
     * if it expires.
     */
    "refresh_token"?: string;

    /**
     * Expiry is the optional expiration time of the access token.
     * 
     * If zero, [TokenSource] implementations will reuse the same
     * token forever and RefreshToken or equivalent
     * mechanisms for that TokenSource will not be used.
     */
    "expiry"?: string;

    /**
     * ExpiresIn is the OAuth2 wire format "expires_in" field,
     * which specifies how many seconds later the token expires,
     * relative to an unknown time base approximately around "now".
     * It is the application's responsibility to populate
     * `Expiry` from `ExpiresIn` when required.
     */
    "expires_in"?: number;
}
