/**
 * Generated by orval 🍺
 * Do not edit manually.
 * YStreamUtils.Docker | v1
 * OpenAPI spec version: 1.0.0
 */
export type ApplicationPlatform = typeof ApplicationPlatform[keyof typeof ApplicationPlatform];


export const ApplicationPlatform = {
  windows: 'windows',
  docker: 'docker',
  linux: 'linux',
  macOS: 'macOS',
  unknown: 'unknown',
} as const;

export interface ConnectUrlResponse {
  url: string;
}

export interface DocumentationConfig {
  description: string;
}

export interface EnvironmentPlatformResponse {
  platform: ApplicationPlatform;
}

export type EventKey = typeof EventKey[keyof typeof EventKey];


export const EventKey = {
  'app:manual': 'app:manual',
  'stream:chat_message': 'stream:chat_message',
  'stream:youtube:superchat': 'stream:youtube:superchat',
  'app:log': 'app:log',
} as const;

export type Platform = typeof Platform[keyof typeof Platform];


export const Platform = {
  youtube: 'youtube',
  twitch: 'twitch',
} as const;

export interface OAuthConfigInput {
  tenantId: string;
  platform: Platform;
  clientId: string;
  clientSecret: string;
}

export interface SourceConfig {
  repository: string;
  owner: string;
}

export interface PluginManifest {
  name: string;
  version: string;
  entryPoint: string;
  permissions: string[];
  authors: string[];
  source: SourceConfig;
  documentation: DocumentationConfig;
}

export interface PluginSettings {
  repos?: string[];
}

export interface RegisterScriptRequest {
  topic: EventKey;
  scriptId: string;
  rawJsString: string;
}

export interface ScriptMetadataResponse {
  definitions: string;
}

export interface UiSettings {
  theme?: string;
  color?: string;
  fullyCloseSidebar?: boolean;
}

export interface Settings {
  ui?: UiSettings;
  plugins?: PluginSettings;
}

export interface UserProfile {
  displayName: string;
  avatarUrl: string;
  channelId: string;
  handle: string;
}

export interface UserScript {
  scriptId?: string;
  topic?: EventKey;
  rawJsString?: string;
  isEnabled?: boolean;
}

export type HasAuthConfigParams = {
platform: Platform;
};

export type YoutubeLoginUrlParams = {
tenantId: string;
role: string;
};

export type GetApiAuthCallbackYoutubeParams = {
code: string;
state: string;
};

export type GetProfileParams = {
tenantId: string;
platform: Platform;
isBot: boolean;
};

export type getSettingsResponse200 = {
  data: Settings
  status: 200
}

export type getSettingsResponseSuccess = (getSettingsResponse200) & {
  headers: Headers;
};
;

export type getSettingsResponse = (getSettingsResponseSuccess)

export const getGetSettingsUrl = () => {




  return `/api/settings`
}

export const getSettings = async ( options?: RequestInit): Promise<getSettingsResponse> => {

  const res = await fetch(getGetSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSettingsResponse
}



export type saveSettingsResponse200 = {
  data: Settings
  status: 200
}

export type saveSettingsResponseSuccess = (saveSettingsResponse200) & {
  headers: Headers;
};
;

export type saveSettingsResponse = (saveSettingsResponseSuccess)

export const getSaveSettingsUrl = () => {




  return `/api/settings`
}

export const saveSettings = async (settings: Settings, options?: RequestInit): Promise<saveSettingsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSaveSettingsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(settings)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: saveSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveSettingsResponse
}



export type fetchAllRegistryPluginsResponse200 = {
  data: PluginManifest[]
  status: 200
}

export type fetchAllRegistryPluginsResponseSuccess = (fetchAllRegistryPluginsResponse200) & {
  headers: Headers;
};
;

export type fetchAllRegistryPluginsResponse = (fetchAllRegistryPluginsResponseSuccess)

export const getFetchAllRegistryPluginsUrl = () => {




  return `/api/plugins/registry`
}

export const fetchAllRegistryPlugins = async ( options?: RequestInit): Promise<fetchAllRegistryPluginsResponse> => {

  const res = await fetch(getFetchAllRegistryPluginsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: fetchAllRegistryPluginsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as fetchAllRegistryPluginsResponse
}



export type downloadAndInstallPluginResponse200 = {
  data: void
  status: 200
}

export type downloadAndInstallPluginResponseSuccess = (downloadAndInstallPluginResponse200) & {
  headers: Headers;
};
;

export type downloadAndInstallPluginResponse = (downloadAndInstallPluginResponseSuccess)

export const getDownloadAndInstallPluginUrl = () => {




  return `/api/plugins/install`
}

export const downloadAndInstallPlugin = async (pluginManifest: PluginManifest, options?: RequestInit): Promise<downloadAndInstallPluginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getDownloadAndInstallPluginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pluginManifest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: downloadAndInstallPluginResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as downloadAndInstallPluginResponse
}



export type getInstalledPluginsResponse200 = {
  data: PluginManifest
  status: 200
}

export type getInstalledPluginsResponseSuccess = (getInstalledPluginsResponse200) & {
  headers: Headers;
};
;

export type getInstalledPluginsResponse = (getInstalledPluginsResponseSuccess)

export const getGetInstalledPluginsUrl = () => {




  return `/api/plugins/installed`
}

export const getInstalledPlugins = async ( options?: RequestInit): Promise<getInstalledPluginsResponse> => {

  const res = await fetch(getGetInstalledPluginsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getInstalledPluginsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getInstalledPluginsResponse
}



export type registerScriptAndBindToBusResponse200 = {
  data: void
  status: 200
}

export type registerScriptAndBindToBusResponseSuccess = (registerScriptAndBindToBusResponse200) & {
  headers: Headers;
};
;

export type registerScriptAndBindToBusResponse = (registerScriptAndBindToBusResponseSuccess)

export const getRegisterScriptAndBindToBusUrl = () => {




  return `/api/scripts/register`
}

export const registerScriptAndBindToBus = async (registerScriptRequest: RegisterScriptRequest, options?: RequestInit): Promise<registerScriptAndBindToBusResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getRegisterScriptAndBindToBusUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerScriptRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerScriptAndBindToBusResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as registerScriptAndBindToBusResponse
}



export type getMonacoEnvironmentResponse200 = {
  data: ScriptMetadataResponse
  status: 200
}

export type getMonacoEnvironmentResponseSuccess = (getMonacoEnvironmentResponse200) & {
  headers: Headers;
};
;

export type getMonacoEnvironmentResponse = (getMonacoEnvironmentResponseSuccess)

export const getGetMonacoEnvironmentUrl = (topic: EventKey,) => {




  return `/api/scripts/monaco-env/${topic}`
}

export const getMonacoEnvironment = async (topic: EventKey, options?: RequestInit): Promise<getMonacoEnvironmentResponse> => {

  const res = await fetch(getGetMonacoEnvironmentUrl(topic),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonacoEnvironmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonacoEnvironmentResponse
}



export type getScriptByIdResponse200 = {
  data: UserScript
  status: 200
}

export type getScriptByIdResponseSuccess = (getScriptByIdResponse200) & {
  headers: Headers;
};
;

export type getScriptByIdResponse = (getScriptByIdResponseSuccess)

export const getGetScriptByIdUrl = (scriptId: string,) => {




  return `/api/scripts/${scriptId}`
}

export const getScriptById = async (scriptId: string, options?: RequestInit): Promise<getScriptByIdResponse> => {

  const res = await fetch(getGetScriptByIdUrl(scriptId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getScriptByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getScriptByIdResponse
}



export type deleteScriptByIdResponse200 = {
  data: void
  status: 200
}

export type deleteScriptByIdResponseSuccess = (deleteScriptByIdResponse200) & {
  headers: Headers;
};
;

export type deleteScriptByIdResponse = (deleteScriptByIdResponseSuccess)

export const getDeleteScriptByIdUrl = (scriptId: string,) => {




  return `/api/scripts/${scriptId}`
}

export const deleteScriptById = async (scriptId: string, options?: RequestInit): Promise<deleteScriptByIdResponse> => {

  const res = await fetch(getDeleteScriptByIdUrl(scriptId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteScriptByIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteScriptByIdResponse
}



export type getAllScriptsResponse200 = {
  data: UserScript[]
  status: 200
}

export type getAllScriptsResponseSuccess = (getAllScriptsResponse200) & {
  headers: Headers;
};
;

export type getAllScriptsResponse = (getAllScriptsResponseSuccess)

export const getGetAllScriptsUrl = () => {




  return `/api/scripts`
}

export const getAllScripts = async ( options?: RequestInit): Promise<getAllScriptsResponse> => {

  const res = await fetch(getGetAllScriptsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllScriptsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllScriptsResponse
}



export type saveScriptResponse200 = {
  data: void
  status: 200
}

export type saveScriptResponseSuccess = (saveScriptResponse200) & {
  headers: Headers;
};
;

export type saveScriptResponse = (saveScriptResponseSuccess)

export const getSaveScriptUrl = () => {




  return `/api/scripts/save`
}

export const saveScript = async (userScript: UserScript, options?: RequestInit): Promise<saveScriptResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSaveScriptUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(userScript)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: saveScriptResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as saveScriptResponse
}



export type invokeScriptTestResponse200 = {
  data: void
  status: 200
}

export type invokeScriptTestResponseSuccess = (invokeScriptTestResponse200) & {
  headers: Headers;
};
;

export type invokeScriptTestResponse = (invokeScriptTestResponseSuccess)

export const getInvokeScriptTestUrl = () => {




  return `/api/script/test/invoke`
}

export const invokeScriptTest = async ( options?: RequestInit): Promise<invokeScriptTestResponse> => {

  const res = await fetch(getInvokeScriptTestUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: invokeScriptTestResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as invokeScriptTestResponse
}



export type invokeManualEventResponse200 = {
  data: void
  status: 200
}

export type invokeManualEventResponseSuccess = (invokeManualEventResponse200) & {
  headers: Headers;
};
;

export type invokeManualEventResponse = (invokeManualEventResponseSuccess)

export const getInvokeManualEventUrl = () => {




  return `/api/events/invoke`
}

export const invokeManualEvent = async ( options?: RequestInit): Promise<invokeManualEventResponse> => {

  const res = await fetch(getInvokeManualEventUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: invokeManualEventResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as invokeManualEventResponse
}



export type listenToGlobalEventBusStreamResponse200 = {
  data: void
  status: 200
}

export type listenToGlobalEventBusStreamResponseSuccess = (listenToGlobalEventBusStreamResponse200) & {
  headers: Headers;
};
;

export type listenToGlobalEventBusStreamResponse = (listenToGlobalEventBusStreamResponseSuccess)

export const getListenToGlobalEventBusStreamUrl = () => {




  return `/api/events/listen`
}

export const listenToGlobalEventBusStream = async ( options?: RequestInit): Promise<listenToGlobalEventBusStreamResponse> => {

  const res = await fetch(getListenToGlobalEventBusStreamUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listenToGlobalEventBusStreamResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as listenToGlobalEventBusStreamResponse
}



export type saveAuthConfigResponse200 = {
  data: string
  status: 200
}

export type saveAuthConfigResponseSuccess = (saveAuthConfigResponse200) & {
  headers: Headers;
};
;

export type saveAuthConfigResponse = (saveAuthConfigResponseSuccess)

export const getSaveAuthConfigUrl = () => {




  return `/api/auth/config`
}

export const saveAuthConfig = async (oAuthConfigInput: OAuthConfigInput, options?: RequestInit): Promise<saveAuthConfigResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSaveAuthConfigUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(oAuthConfigInput)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: saveAuthConfigResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveAuthConfigResponse
}



export type hasAuthConfigResponse200 = {
  data: boolean
  status: 200
}

export type hasAuthConfigResponseSuccess = (hasAuthConfigResponse200) & {
  headers: Headers;
};
;

export type hasAuthConfigResponse = (hasAuthConfigResponseSuccess)

export const getHasAuthConfigUrl = (params: HasAuthConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/config?${stringifiedParams}` : `/api/auth/config`
}

export const hasAuthConfig = async (params: HasAuthConfigParams, options?: RequestInit): Promise<hasAuthConfigResponse> => {

  const res = await fetch(getHasAuthConfigUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: hasAuthConfigResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as hasAuthConfigResponse
}



export type youtubeLoginUrlResponse200 = {
  data: ConnectUrlResponse
  status: 200
}

export type youtubeLoginUrlResponseSuccess = (youtubeLoginUrlResponse200) & {
  headers: Headers;
};
;

export type youtubeLoginUrlResponse = (youtubeLoginUrlResponseSuccess)

export const getYoutubeLoginUrlUrl = (params: YoutubeLoginUrlParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/login/youtube?${stringifiedParams}` : `/api/auth/login/youtube`
}

export const youtubeLoginUrl = async (params: YoutubeLoginUrlParams, options?: RequestInit): Promise<youtubeLoginUrlResponse> => {

  const res = await fetch(getYoutubeLoginUrlUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: youtubeLoginUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as youtubeLoginUrlResponse
}



export type getApiAuthCallbackYoutubeResponse200 = {
  data: void
  status: 200
}

export type getApiAuthCallbackYoutubeResponseSuccess = (getApiAuthCallbackYoutubeResponse200) & {
  headers: Headers;
};
;

export type getApiAuthCallbackYoutubeResponse = (getApiAuthCallbackYoutubeResponseSuccess)

export const getGetApiAuthCallbackYoutubeUrl = (params: GetApiAuthCallbackYoutubeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/callback/youtube?${stringifiedParams}` : `/api/auth/callback/youtube`
}

export const getApiAuthCallbackYoutube = async (params: GetApiAuthCallbackYoutubeParams, options?: RequestInit): Promise<getApiAuthCallbackYoutubeResponse> => {

  const res = await fetch(getGetApiAuthCallbackYoutubeUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiAuthCallbackYoutubeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiAuthCallbackYoutubeResponse
}



export type getProfileResponse200 = {
  data: UserProfile
  status: 200
}

export type getProfileResponseSuccess = (getProfileResponse200) & {
  headers: Headers;
};
;

export type getProfileResponse = (getProfileResponseSuccess)

export const getGetProfileUrl = (params: GetProfileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/profile?${stringifiedParams}` : `/api/auth/profile`
}

export const getProfile = async (params: GetProfileParams, options?: RequestInit): Promise<getProfileResponse> => {

  const res = await fetch(getGetProfileUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProfileResponse
}



export type getRunningEnvironmentResponse200 = {
  data: EnvironmentPlatformResponse
  status: 200
}

export type getRunningEnvironmentResponseSuccess = (getRunningEnvironmentResponse200) & {
  headers: Headers;
};
;

export type getRunningEnvironmentResponse = (getRunningEnvironmentResponseSuccess)

export const getGetRunningEnvironmentUrl = () => {




  return `/api/environment/platform`
}

export const getRunningEnvironment = async ( options?: RequestInit): Promise<getRunningEnvironmentResponse> => {

  const res = await fetch(getGetRunningEnvironmentUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRunningEnvironmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRunningEnvironmentResponse
}



export type getApiHealthResponse200 = {
  data: void
  status: 200
}

export type getApiHealthResponseSuccess = (getApiHealthResponse200) & {
  headers: Headers;
};
;

export type getApiHealthResponse = (getApiHealthResponseSuccess)

export const getGetApiHealthUrl = () => {




  return `/api/health`
}

export const getApiHealth = async ( options?: RequestInit): Promise<getApiHealthResponse> => {

  const res = await fetch(getGetApiHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiHealthResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiHealthResponse
}



export type getApiVersionResponse200 = {
  data: void
  status: 200
}

export type getApiVersionResponseSuccess = (getApiVersionResponse200) & {
  headers: Headers;
};
;

export type getApiVersionResponse = (getApiVersionResponseSuccess)

export const getGetApiVersionUrl = () => {




  return `/api/version`
}

export const getApiVersion = async ( options?: RequestInit): Promise<getApiVersionResponse> => {

  const res = await fetch(getGetApiVersionUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiVersionResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiVersionResponse
}
